# airflow-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-sa
  namespace: airflow

---

# mlflow-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mlflow
  name: airflow-access
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["create", "get", "list", "watch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-access-binding
  namespace: mlflow
subjects:
- kind: ServiceAccount
  name: airflow-sa
  namespace: airflow
roleRef:
  kind: Role
  name: airflow-access
  apiGroup: rbac.authorization.k8s.io

